{% set name = "mistralai" %}
{% set version = "1.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3df9e403c31a756ec79e78df25ee73cea3eb15f86693773e16b16adaf59c9b8a

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - eval-type-backport >=0.2.0
    - httpx >=0.28.1
    - pydantic >=2.10.3
    - python-dateutil >=2.8.2
    - typing-inspection >=0.4.0
    - pyyaml >=6.0.2,<7.0.0
    - invoke >=2.2.0,<3.0.0
  run_constrained:
    # gcp
    - google-auth >=2.27.0
    - requests >=2.32.3
    # agents
    - mcp >=1.0,<2.0  # [py>=310]
    - griffe >=1.7.3,<2.0
    - authlib >=1.5.2,<2.0

test:
  imports:
    - mistralai
    - mistralai.models
    - mistralai.client
    - mistralai.utils
  requires:
    - pip
    - pytest >=8.2.2
  commands:
    - pip check

about:
  home: https://github.com/mistralai/client-python
  summary: Python client library for Mistral AI platform
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Mistral AI is a leading open-source generative AI platform.
    This is the official Python client library for Mistral AI,
    which provides a simple and efficient way to interact with
    the Mistral API.
  doc_url: https://github.com/mistralai/client-python
  dev_url: https://github.com/mistralai/client-python

extra:
  recipe-maintainers:
    - jtpio
